### ISSUE TITLE
CTD/Crash after ending turn/Planetary Ecology report on forest growth

### ISSUE THREAD

**Issue by ArneHD** [induktio/thinker#68] opened 2024-05-18 14:20 UTC
I'm experiencing a crash when selecting end turn, the crash appears to happen either after or during the end turn report on forest/kelp growth.

This crash appears to happen sometime into the game and occurs both with "Thinker Mod develop build (May 16 2024)" and with the release 4.2 version.

I'd appreciate any advice for how to solve or avoid this crash.
Thanks

[debug.txt](https://github.com/induktio/thinker/files/15365610/debug.txt)

**Comment by Vengarr** [comment] 2024-05-20 16:57
Same issue here, I've had the same thing happen several games with the same error code. Reloading prior autosaves does not always help.

[debug.txt](https://github.com/induktio/thinker/files/15379848/debug.txt)

**Comment by Vengarr** [comment] 2024-05-20 17:16
Okay, I think I may have isolated this one. It seems to be caused by the "Energy Market Crash" random event, and it was introduced sometime after 4.1. I'm just guessing, but there might be something wonky in the formula that calculates your new energy reserves. 

Rolling back to 4.1 works, or you can reduce your energy credits below 1000 to keep the event from firing. 

Here's a save for debugging purposes: [fffff.zip](https://github.com/induktio/thinker/files/15379987/fffff.zip)

**Comment by induktio** [comment] 2024-05-22 15:44
Good that you found it, there was a minor bug with the patched code related to event_market_crash option which apparently crashed the game. This should be fixed in May 22 build so you can reload the previous savegames and play the game as usual. Also the notification icon for this event is changed to genwarning_sm.pcx while it was previously markbm_sm.pcx.

**Closed** 2024-06-30 13:55 UTC
