### ISSUE TITLE
mod_base_production has side effects

### ISSUE THREAD

**Issue by tnevolin** [induktio/thinker#19] opened 2021-04-08 15:43 UTC
Original function proposes production choice and nothing else
.text:004F81A0 base_prod_choice proc near              ; CODE XREF: base_reset+C1↑p

mod_base_production modifies original function.
It also calls consider_hurry which may modify base state. Original function doesn't do that.

It would be nice if you stick to original function purpose. Then I can safely redirect to your function for production suggestion.
Currently I have to modify your function to ensure it doesn't silently modify base state under the hood.

**Comment by induktio** [comment] 2021-04-08 16:24
The problem is these things don't have any well-defined APIs to follow. The implementation of consider_hurry basically has to modify base state in some way to accomplish it's goal. This shouldn't affect player bases ever because the functions don't get called on them. Maybe someday if base_reset gets rewritten the thing could be restructured in a cleaner way but currently I don't see how this interferes with how Thinker works.

**Comment by tnevolin** [comment] 2021-04-08 16:27
That does not affect human player at all. This affects computer players for which both you and I create AI routines. I do not absolutely mind rewriting your code as needed. However, one of my priorities is to keep it intact if possible to make sure users experience same AI behavior.

**Comment by induktio** [comment] 2021-04-08 16:48
Are you proposing to add some kind of a way for multiple AI routines to suggest base production? What would be the benefit for players, e.g. multiple strategy types for AI factions? Not sure what's the purpose there. Note that I have not been specifically reviewing stuff in other versions unless that code gets merged here.

**Comment by tnevolin** [comment] 2021-04-08 18:29
Let me explain it again as clear as I can.

- I am not forcing you to do anything. This is just a (I hope friendly) suggestion.
- I can perfectly manage your legacy and modify it to my needs. You do not block me.
- At the same time I try to preserve borrowed functionality intact for the sake of users whenever I can. The less variation in well used routines they see the easier for them to follow.
- Whether you benefit from that - I don't know. I would guess you were interested in advertising your functionality in as much mods covering as many user base as possible. If not than it is completely fine with me.

So if you want me to credit you for AI modifications you may be interested to modify your code in a way that is easy to reuse without altering. That's all.

**Comment by induktio** [comment] 2021-04-08 19:13
Just pointing out there area some games with APIs for pluggable AI modules, for example [OpenRA](https://docs.openra.net/en/latest/release/lua/). But development resources are limited and getting to that level is still quite a long ways off. So it's mainly about prioritization.

**Comment by induktio** [comment] 2021-04-18 07:25
Probably should do something long term that enables more pluggable AI modules for bases for example. You can also look up ROTP, they also have multiple AI support.

But looking at the WTP code, it seems to mix up vanilla AI stuff, something else and Thinker base production logic for the same faction which is not the way it was designed to be. Doing so will almost surely mess up some AI priorities because they will not stay consistent for the same faction. There's probably other stuff like that in WTP code, not sure. Now you might want to run different AIs side-by-side on different factions and then observe the results. Otherwise I don't see any point in supporting or recommending features that just go against the design logic for Thinker here. AI design is kind of brittle for these kind of games, if one part doesn't do what it's supposed to be, then the coordination can fail badly.

**Comment by tnevolin** [comment] 2021-04-18 11:36
Does it hurt your feeling seeing that your production suggestions are not used 100% of the time? Let me know if so. I will think of something.

**Comment by induktio** [comment] 2021-04-18 11:53
Well, I'm not going to recommend any stuff that mixes up vanilla AI base code there. :) Thinker has been doing that stuff since the first version. It was also the first major AI feature that was implemented in this mod.

**Comment by tnevolin** [comment] 2021-04-18 15:25
Thanks.

**Closed** 2021-04-19 13:41 UTC
