### ISSUE TITLE
v4.6 Units break out of Full Automate more often

### ISSUE THREAD

**Issue by makotech222** [induktio/thinker#79] opened 2024-10-07 20:31 UTC
Since update, it seems like units i set to Full Automate will have that order cancelled far more often for unknown reasons, requiring me to set them back to Full Automate.

**Comment by induktio** [comment] 2024-10-08 15:37
I have not seen anyone else report this issue yet. Would need more information on how to reproduce it or maybe savegames?

**Comment by makotech222** [comment] 2024-10-08 15:51
I noticed it a lot with copter units; when they attacked someone, it very often broke out of Automate and required me to reset it, attacked again, then reset again multiple times a turn.

**Comment by makotech222** [comment] 2024-10-11 14:54
I assumed it was from this change:

 -Thinker also manages automated player combat units, probes and transports when this is enabled from options. 
 
 I don't remember it every being this bad. I was holding Shift+A down while my units were running their turn because of how many were dropping out of automate. The new AI does do a hell of a lot better when at war, though. I'll see what happens if I turn that off

**Comment by makotech222** [comment] 2024-10-12 03:55
Some observations:

- It seems like Thinker-controlled units are more likely to make attacks, and thus trigger the 'break out of automation'. Coptors in particular attacking from a city tile don't get broken, but if they are attacking while away from a city, they will constantly break out after every attack. Other unit types seem to have similar triggers
- Formers on Thinker-control never seem to remove fungus for some reason. I also never see them build farms or solar collectors. They only build roads and boreholes and forests, it seems.

**Comment by induktio** [comment] 2024-10-13 11:56
Yeah not sure about the fix for this automation issue since it probably requires some rewrites, but might be done later.

AI formers follow specific terraforming strategy that is dependent on available techs and bonuses. In particular they have flags for keep_fungus and plant_fungus that determine what is being done on those tiles. Early on forest produces more, so they will plant it instead but after a while fungus production bonuses will overtake it, so more fungus tiles are being used. Farms+solar are built less often, usually on nutrient bonus tiles. Maybe it could be adjusted a little.

**Closed** 2024-10-14 12:21 UTC
