### ISSUE TITLE
mouse scroll behaviour bug cause possibly found

### ISSUE THREAD

**Issue by ramseysparrow** [induktio/thinker#60] opened 2024-03-20 16:41 UTC
Firstly, a huge thank you for polishing one of my favourite games up to ying-yang – it's an amazing experience. 

Beyond your countless AI improvements, the simple ability to scroll-zoom and mouse-drag around smoothly from PRAX is the single most groundbreaking change to how the game feels moment to moment.

I experience inconsistent behaviour with it, though, and have read a few related issue reports from others here and in PRAX, but I don't think the cause was fully narrowed down, so here's what I found:

- With minimap set to global (default) the mouse-dragging and zoom-scrolling works flawlessly. 
- When switched to detailed, it immediately breaks and causes scrolling to act as up/down command.
I can only suspect that's due to detailed mode having its own zoom in and out controls under right mouse click.

Goes without saying, if there is a way to fix that, the perfect Alpha Centauri experience completes. 
A shortcut for toggling global/detailed minimap and for zooming it in-out would be double-plus-good ;)

**Comment by induktio** [comment] 2024-03-20 19:45
Good thing to find this small oversight in the mod. 👍

This was related to the earlier issues where the mod didn't determine correctly when the world map has focus. Looks like it can be fixed with a couple of small changes on map_is_visible() function. This is updated in Mar 20 build, so the mouse wheel zoom should only activate when the world map is visible and any units should not be moved by the mouse wheel.

**Comment by ramseysparrow** [comment] 2024-03-20 20:33
Thats right, i remember other threads mentioning the focus issue in relation to dialogue option menus, though never in relation to the minimap mode.

Just to confirm Im understanding this right - are you saying the minimap issue is something you will look into fixing in the future, or something that you already have fixed (you mention today’s date - march 20th)? Apologies, Im not sure if I got your meaning in that part!

**Comment by ramseysparrow** [comment] 2024-03-20 21:27
I believe I figured it out: you're referring to the dev builds, newest one dated today. Will give it a try and report. Thanks.

**Comment by ramseysparrow** [comment] 2024-03-20 22:58
Salutations, brother @induktio. I have tested your newest patch and can confirm that the issue has been fully fixed. I believe your coding principles and my humanitarian ideals will complement each other nicely. Let us form a pact of friendship and explore this planet together.

**Comment by induktio** [comment] 2024-03-21 12:18
Hehe, it's possible there are still some rare situations where the map visibility is not detected correctly. The code could still use some cleanup if there's a better way to do it, so have to think about it.

**Comment by ramseysparrow** [comment] 2024-03-21 19:03
Its been smooth sailing so far, but i will let you know if i run into any exceptions.

**Comment by ramseysparrow** [comment] 2024-03-23 18:51
Hi again. It seems that when using governor in bases, the priority buttons don't highlight as you select them, making it difficult to know what mode the base's governor is in. 

Playing smac in smacx mode with prax.

**Comment by ramseysparrow** [comment] 2024-03-23 19:03
Almost forgot – some shortcuts such as 'show flatten terrain' don't seem to work either and can only be executed from the menu.

**Comment by ramseysparrow** [comment] 2024-03-24 18:00
_"…and they are automatically deselected in the interface"._ 
Though I have actually read through the details.md, it seems that went past me somehow. Good to know, thanks.

About keyboard shortcuts, all I can say is that the one I mentioned seems consistently not to work for me when using Thinker+PRAX with SMAC-in-SMACx setting enabled. It's hardly a deal breaker but this being a place to mention every and al such glitches, here it is. 

One other thing I had happen since was an apparent glitch in the unit designer menu - I created a unit there, a first generation foil, I believe, deleted it and tried creating it again but it would not appear in the base construction menu. As above, just reporting possible weirdness, never in a complain-mode.

By the way the AI is so effing agressive in this mod, seeding bases like maniacs and constantly harassing me with threats for payments and vendettas. They all appear to be total psychopaths now, haha.

**Comment by ramseysparrow** [comment] 2024-03-25 00:10
To add to that, I find that while shortcut for showing patrols (shift + p) works fine, the same for base autoforwarding does not – just like the show flattened terrain command it only works from the menu rather than from a shortcut. No idea why.

**Comment by induktio** [comment] 2024-03-25 16:03
The issue with those other keyboard shortcuts does not seem reproducible without further information. Random shortcuts should not just stop working in the game unless the mods map them to other functions. Something about the system/hardware configuration? Does it occur when either only the original game or original game+PRACX is running? Could even try reinstalling the game and other usual troubleshooting steps.

**Comment by ramseysparrow** [comment] 2024-03-25 17:20
Hard to think of. Windows 11, 11gen intel cpu, rt6800xt, 64gb ram with m4 nvme. 
GOG version of SMACx installed via Galaxy.

In my testing the issues aren't present in Vanilla nor with PRAX installed, and only appear when Thinker is added. 
Does installation order of Thinker and PRAX make a difference? 
I'll let you know if I notice anything else.

**Comment by ramseysparrow** [comment] 2024-03-25 19:12
Ok, so I have now done some fundamental testing and found the pattern. Surprise surprise, the cause is the crossfire engine executive. I don't know what changes crossfire engine had brought, but seeing as both PRAX and Thinker utilise it as the base, the pattern seems to make sense. Test results below.

---

Keyboard shortcuts affected: show flat terrain, show autoforward routes
Keyboard shortcut issues present YES / NO ?

vanilla, terran.exe 		> NO
vanilla, terranx.exe		> YES
-
terran.exe (+thinker)	> NO
terranx.exe (+thinker)	> YES
thinker.exe			> YES
-
terran.exe (+PRAX)	> YES
terranx.exe (+PRAX)	> does not start at all

**Comment by induktio** [comment] 2024-03-25 19:27
I'm not sure what do you mean by terran.exe since it is not possible to use Thinker with this binary as it would start the game without expansion. Only terranx.exe for Alien Crossfire is supported even when using smac_only mode. Game version menu (Ctrl+F4) will always show if Thinker has been loaded in the game. You can use PRACX with terran.exe but it also has a separate dll for this purpose. To know if PRACX has been loaded, one would need to check the Menu button on world map since PRACX always adds an extra menu entry there. Anyway if this bug also appears on the original game, there's some chances it has been mentioned on other forums, but not sure now. It's still not reproducible without some further details though.

**Comment by ramseysparrow** [comment] 2024-03-25 19:46
Yes, I'm aware of everything you just mentioned and I'm not only analyzing thinker here, but rather all possible scenarios starting from the simplest ones at vanilla level.
The bottom line is that it's the crossfire version of the game (vanilla, thinker, prax, thinker+prax version, it doesn't matter) that causes these two shortcuts to not be working. So it's not Thinker that's at fault.

I would struggle to think of how my individual hardware could affect this. Only thing coming to my mind is that perhaps other people did not use shortcuts for those two much and it could have gone unnoticed. 

All in all that's about as much detail as I can possibly give. It's a strange one for sure.

**Closed** 2024-09-03 16:51 UTC
